//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找已本地化的字符串等等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class IZWebFileManagerResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IZWebFileManagerResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.IZWebFileManagerResource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找重写当前线程的 CurrentUICulture 
        /// 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Arrange Icons By 的本地化字符串。
        /// </summary>
        internal static string Arrange_Icons_By {
            get {
                return ResourceManager.GetString("Arrange_Icons_By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot Complete Operation. 的本地化字符串。
        /// </summary>
        internal static string CannotCompleteOperation {
            get {
                return ResourceManager.GetString("CannotCompleteOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot find file, Make sure the path is correct. 的本地化字符串。
        /// </summary>
        internal static string CannotFindFile {
            get {
                return ResourceManager.GetString("CannotFindFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot rename file: A file with the name you specified already exists. Specify a different file name. 的本地化字符串。
        /// </summary>
        internal static string CannotRenameFile {
            get {
                return ResourceManager.GetString("CannotRenameFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy 的本地化字符串。
        /// </summary>
        internal static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New 的本地化字符串。
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Folder 的本地化字符串。
        /// </summary>
        internal static string Create_New_Folder {
            get {
                return ResourceManager.GetString("Create_New_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Date Modified 的本地化字符串。
        /// </summary>
        internal static string Date_Modified {
            get {
                return ResourceManager.GetString("Date_Modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to delete selected items? 的本地化字符串。
        /// </summary>
        internal static string DeleteConfirm {
            get {
                return ResourceManager.GetString("DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The destination folder is a subfolder of the source folder. 的本地化字符串。
        /// </summary>
        internal static string DestinationFolderIsSubfolder {
            get {
                return ResourceManager.GetString("DestinationFolderIsSubfolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Details 的本地化字符串。
        /// </summary>
        internal static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download 的本地化字符串。
        /// </summary>
        internal static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File Folder 的本地化字符串。
        /// </summary>
        internal static string File_Folder {
            get {
                return ResourceManager.GetString("File_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Folder Path 的本地化字符串。
        /// </summary>
        internal static string Folder_Path {
            get {
                return ResourceManager.GetString("Folder_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Icons 的本地化字符串。
        /// </summary>
        internal static string Icons {
            get {
                return ResourceManager.GetString("Icons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Move 的本地化字符串。
        /// </summary>
        internal static string Move {
            get {
                return ResourceManager.GetString("Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You must type a file name. 的本地化字符串。
        /// </summary>
        internal static string MustTypeFileName {
            get {
                return ResourceManager.GetString("MustTypeFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Folder 的本地化字符串。
        /// </summary>
        internal static string New_Folder {
            get {
                return ResourceManager.GetString("New_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Folder 的本地化字符串。
        /// </summary>
        internal static string New_Folder_Name {
            get {
                return ResourceManager.GetString("New_Folder_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A file name cannot contain any of the following characters: \/:*?&quot;&lt;&gt;| 的本地化字符串。
        /// </summary>
        internal static string NotAllowedCharacters {
            get {
                return ResourceManager.GetString("NotAllowedCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open 的本地化字符串。
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refresh 的本地化字符串。
        /// </summary>
        internal static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rename 的本地化字符串。
        /// </summary>
        internal static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search 的本地化字符串。
        /// </summary>
        internal static string SearchWatermark {
            get {
                return ResourceManager.GetString("SearchWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select destination directory 的本地化字符串。
        /// </summary>
        internal static string SelectDestination {
            get {
                return ResourceManager.GetString("SelectDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Size 的本地化字符串。
        /// </summary>
        internal static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Submit 的本地化字符串。
        /// </summary>
        internal static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Thumbnails 的本地化字符串。
        /// </summary>
        internal static string Thumbnails {
            get {
                return ResourceManager.GetString("Thumbnails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type 的本地化字符串。
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Up 的本地化字符串。
        /// </summary>
        internal static string Up {
            get {
                return ResourceManager.GetString("Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Upload Another File 的本地化字符串。
        /// </summary>
        internal static string Upload_Another_File {
            get {
                return ResourceManager.GetString("Upload_Another_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Upload File 的本地化字符串。
        /// </summary>
        internal static string Upload_File {
            get {
                return ResourceManager.GetString("Upload_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove 的本地化字符串。
        /// </summary>
        internal static string Upload_File_Remove {
            get {
                return ResourceManager.GetString("Upload_File_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View 的本地化字符串。
        /// </summary>
        internal static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
    }
}
